import { Header } from "@/components/Header";
import { MenuLateral } from "@/components/MenuLateral";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className={`h-full bg-gray-200 ${inter.className}`}>
        <Header />
        <div className="flex h-full ">
          <MenuLateral />
          <div className="flex-1 px-8 pt-8 bg-white">{children}</div>
        </div>
      </body>
    </html>
  );
}
